<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository
{
    public function findAllOrderedForUser(User $user)
    {
        $queryBuilder = $this->createQueryBuilder('w')
            ->join('w.user','u')
            ->where('u.id = :id')
            ->addOrderBy('w.id', 'DESC')
            ->setParameter('id', $user->getId());

        return $queryBuilder->getMaxResults();
    }

    public function findOneWishForUser($username, $idWish)
    {
        $query = $this->createQueryBuilder('w')
            ->join('w.user','u')
            ->where('u.username = :username')
            ->andWhere('w.id = :idWish')
            ->setParameter('username', $username)
            ->setParameter('idWish', $idWish)
            ->getQuery();

        return $query->getSingleResult();
    }
}
